pipeline:
  test:
    image: node:8
    commands:
      - npm install
      - npm run lint
      - npm test
      - npm run validate-yaml
      - npm run validate-openapi-spec

  slack:
    image: plugins/slack
    username: drone
    secrets: [slack_webhook]
    when:
      event: [pull_request]
