pipeline:
  build:
    image: node:8
    commands:
      - npm install

  lint:
    group: test
    image: node:8
    commands:
      - npm run lint

  test:
    group: test
    image: node:8
    commands:
      - npm test

  validate-spec:
    group: test
    image: node:8
    commands:
      - npm run validate-yaml
      - npm run validate-openapi-spec

  start-smoke-test-instance:
    image: node:8
    detach: true
    environment:
      - NODE_ENV=production
    commands:
      - npm start

  run-smoke-test:
    image: node:8
    environment:
      - SMOKE_TARGET_HOST=start-smoke-test-instance
    commands:
      - curl -L https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -o /usr/local/bin/jq
      - chmod +x /usr/local/bin/jq
      - test/smoke/run.sh

services:
  database:
    image: bitnami/mongodb
    environment:
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=realmq
      - MONGODB_PASSWORD=realmq
      - MONGODB_DATABASE=realmq
