rules:
  unicorn/prefer-module: off
  import/extensions: off
  indent:
    - error
    - 2
  comma-dangle:
    - error
    - always-multiline
overrides:
  - files:
    - src/**/*.test.js
    - src/**/*.spec.js
    env:
      jest: true
  - files:
      - src/api/admin/v1/routes/**/*.js
      - src/api/client/v1/routes/**/*.js
    rules:
      unicorn/filename-case: off
