extends:
  - xo/esnext
  - ./node_modules/xo/config/plugins.js
rules:
  indent:
    - error
    - 2
  comma-dangle:
    - error
    - always-multiline
overrides:
  - files:
    - src/**/*.test.js
    - src/**/*.spec.js
    env:
      jest: true
