swagger: "2.0"

info:
  title: RealMQ admin api
  version: 0.3.0

paths: !includeMerged
  - routes/realms.yaml
  - routes/realms/{id}.yaml
  - routes/realms/{realmId}/tokens.yaml
  - routes/realms/{realmId}/users.yaml
  - routes/realms/{realmId}/channels.yaml
  - routes/realms/{realmId}/subscriptions.yaml
  - routes/version.yaml

definitions: !include openapi/definitions.yaml
parameters: !include openapi/parameters.yaml
securityDefinitions: !include openapi/security-definitions.yaml
security:
  - apiKeyScheme: [ ]
