swagger: "2.0"

info:
  title: RealMQ admin api
  version: 0.1.0

paths:
  /accounts: !include routes/accounts.yaml
  /realms: !include routes/realms.yaml
  /version: !include routes/version.yaml

definitions: !include openapi/definitions.yaml
parameters: !include openapi/parameters.yaml
securityDefinitions: !include openapi/security-definitions.yaml
security:
  - accountCredentialsScheme: []
